### ISSUE TITLE
Setup Github as "kanban" working board

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/wg-governance#1]
As discussed Sunday in Montevideo:

 1. [x] Add projects to manage regular work-issues
 2. [x] set up milestones per triage call
 3. [ ] add labels for management

**Comment by gnunicorn** [comment]
Re 1/3: I'd suggest the following columns: `Backlog -> ToDo -> In Progress -> In Review -> Done` - where: 
 - everything starts in `Backlog`
 - only the triage call can move from backlog to ToDo, when ever the task is clearly enough defined in scope and needs that it can be done without further communication
 - anything in ToDo can be self-assigned and moved into "In Progress" at any point (if not assigned yet)
 - everything in `In Progress` and `In Review` _must have an assignee_ (someone, who pushes it forward - a steward -  not necessarily the one actually doing it)
 - Any ticket in the project must start with a verb

---

For UX reasons, I have also had projects move things from right to left, meaning that your eyes start at the completed and achieved work (reading from the left) and are not first blasted with the ever growing backlog. It is counter-intuitive at first, but actually quite a bit more helpful as it focusses on "getting things done" rather than "things to do". If you are up for it, I'd suggest we try that here as well (it is only a UI thing).

**Comment by mgattozzi** [comment]
I am fine with right to left since I read a decent amount of manga. We can experiment and move back to left to right if people don't like it.

**Comment by mgattozzi** [comment]
Actually looks like I don't have the perms to do the project board. cc/ @nikomatsakis or @Manishearth

**Comment by Manishearth** [comment]
I'll do it.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/wg-governance/projects/1
