### ISSUE TITLE
Domain WG Applicant: Rust gamedev

### ISSUE THREAD

**Issue by skade** [rust-lang/wg-governance#10]
This issue acts as a tracking issue and log for the application of a gamedev domain WG.

Details can be found here:
https://internals.rust-lang.org/t/rust-gamedev-wg-application-discussion/10230
https://internals.rust-lang.org/t/enabling-the-formation-of-new-working-groups/10218/4

An older blog post on the same subject here:
https://alexene.github.io/2018/11/15/Rust-and-game-development.html

Formation of a gamedev WG was suggested multiple times, but was blocked off due to a moratorium on creating new WGs.

Current Status:
* [x] Application sent
* [ ] Charta written

The initial goal would be to find a pair of governance WG members to facilitate the formation of the group from our side.

**Comment by AlexEne** [comment]
The bigger list in WG Setup mentions "Decision on Team Comm Channels & Tools & Procedures". 

That can be checked for rust-gamedev:
We decided on those.  It will be the discord room and github issues.  
Discord for discussions (not mandatory reading for anyone).  
If something is important it has to have a github issue. We also briefly considered having RFC process like other WGs have, but for now decided to postpone that decision until it will prove needed. Until then all decisions / proposals will be taken/considered on github issues.

References:
https://github.com/rust-gamedev/wg/issues/2
https://github.com/orgs/rust-gamedev/projects/1#card-22483990
https://github.com/rust-gamedev/wg/issues/3


Charter is a WIP here. I will fix-up the comments by the end of this week:
https://github.com/rust-gamedev/wg/issues/1

**Comment by AlexEne** [comment]
Update: I've merged the initial charter.

**Comment by XAMPPRocky** [comment]
Closing as Game dev is now a Working Group.
