### ISSUE TITLE
Facilitation of Triage meeting #8 (Aug 27th, 2019)

### ISSUE THREAD

**Issue by skade** [rust-lang/wg-governance#19]
We need someone to volunteer running the Triage meeting #8.

Triage facilitation is easy:
* Go through all tickets that were in the Triage list for these 2 weeks, talk about updates
* Go through new tickets
* Find _one_ or at max _two_ good topics for the rest of the time
* Make sure everything that was discussed verbally gets written down

**Comment by XAMPPRocky** [comment]
I can help for this meeting.

**Comment by XAMPPRocky** [comment]
The meeting was cancelled due to small attendance. The only thing we discussed was agreeing that we should finish up the call to action for Governance Research.
