### ISSUE TITLE
Facilitation of Triage meeting #9 (Sept 10th, 2019)

### ISSUE THREAD

**Issue by skade** [rust-lang/wg-governance#20]
We need someone to volunteer running the Triage meeting #9.

Triage facilitation is easy:
* Go through all tickets that were in the Triage list for these 2 weeks, talk about updates
* Go through new tickets
* Find _one_ or at max _two_ good topics for the rest of the time
* Make sure everything that was discussed verbally gets written down

**Comment by gnunicorn** [comment]
Alone in the meeting. Pushed all tickets to the next triage cycle. Nothing else I could do by myself.
