### ISSUE TITLE
Clarify Working Group terminology

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/wg-governance#26]
As was discussed at the last triage meeting, there was pretty clear consensus that the Working Group term as stands is overloaded and that we probably need different terms for the different kinds. Specifically there's domain working groups which essentially function as independent teams, and working groups that are a form of sub team.

### Alternative term suggestions
One term I know is common in other governance structures that use the term working group is [**rapporteur**](https://en.wiktionary.org/wiki/rapporteur) groups. Like working group the term is very general and could work for either type of working group.

_**rapporteur**_: A person appointed by a deliberative body to investigate an issue or a situation, and report back to that body.

**Comment by BatmanAoD** [comment]
Wow, "rapporteur" seems like a close fit, though it's pretty obscure. Also, it might be confusing in verbal communication since most people probably haven't heard it said aloud before (I haven't).

**Comment by XAMPPRocky** [comment]
Well I think with whatever term we pick, we should write a blog post about it, explain the difference we're trying to communicate, and also explain the term itself. I agree that we couldn't just switch terminology without it causing a lot of confusion.

**Comment by XAMPPRocky** [comment]
One term @nikomatsakis brought up at the last meeting was "project groups" for teams that have a specific goal to complete.

**Comment by BatmanAoD** [comment]
In [the FFI-unwind group RFC](https://github.com/rust-lang/rfcs/pull/2797), I use the term "project group". That term is also used in the current draft of Niko's ["shepherded RFCs" RFC](https://github.com/nikomatsakis/project-staged-rfcs/blob/master/rfcs/0001-shepherded-rfcs.md).

Is the governance-WG happy with that term?
