### ISSUE TITLE
Meeting - December 2, 2019

### ISSUE THREAD

**Issue by nellshamrell** [rust-lang/wg-governance#29]
The next meeting of the Rust governance working group will take place at **22:00 UTC on Tuesday, December 3**.

We currently plan to focus on the need for a  [GitHub Access Policy](https://github.com/rust-lang/wg-governance/issues/4). 

We'd like to encourage anyone who's interested, regardless of their
previous experience to come to the `#wg-governance`
channel on Discord to attend the meeting. (Our meetings are done over a video
call with Zoom, but we use the discord channel to organise ourselves).

If there are other issues you would like to see us discuss or discuss with us, please mention them in a comment on this GitHub issue.

Thank you and happy Thanksgiving!

**Comment by XAMPPRocky** [comment]
Closing as the meeting happened. The minutes are available at https://github.com/rust-lang/wg-governance/blob/master/minutes/2019.12.03.md
