### ISSUE TITLE
Create a charter

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/wg-governance#3]
Filing an issue here until we figure out where this kind of thing should go

We should have a public-facing charter or explainer, something like https://github.com/rust-embedded/wg#what-we-do

For that we need to more clearly pin down what our plans are, though :smile:

**Comment by nikomatsakis** [comment]
So @Manishearth and I were talking a bit earlier today. I had ambitions to try and draft a rough draft of a charter but it's proving harder than I thought. So I decided to dump some unstructured thoughts instead for future reference.

I think we want some goals like this:

1. To help the Rust teams in their various efforts at improving their own governance. For example, by participating in the discussions that those teams are holding, and by "circulating" ideas between teams.
2. To help document the current state of Rust governance, good and bad. For example, by surveys (to see what the current problems are) and by talking to the teams to understand better their procedures.
3. To help us get a broader perspective by examining what other communities are doing (both within the open source world and broadly) and trying to bring those lessons into other discussions.

I am not sure how much further we should go. For example, I think a good ultimate goal is to have a kind of "template" for how a Rust team functions. This would include information about how to run a working group, and so forth. This template wouldn't be *proscriptive* -- teams would be encouraged to adapt it to their needs -- but it would incorporate the results of the work above. (Ideally, it would be 'opinionated but flexible', I think, so as to help steer people to ideas that we think work best, without constraining them.)

**Comment by nikomatsakis** [comment]
There are also some questions that I think we want to rule as out of scope for the WG -- or at least for the present? I'm not sure. It'd probably be good to list those.

- **Foundation** -- to what extent do we aim to talk about foundations? 
- **Altering the set of Rust teams themselves** -- I'm not sure about this, I could imagine that arising from surveys or other work we might want to have some conversations along these lines, but it also seems like something we can defer.

**Comment by skade** [comment]
I'm not sure if I want to talk about Foundations per se, but *Money* is definitely an issue. Also, given that a number of Rust foundations or foundation-likes and relationships with FOSS foundations exist, it's an interesting subject itself.

For teams, I'd currently not be active.

Also, I want to stress that a charter is still a living document, with some things being harder then others, we can always come back and iterate.

**Comment by nikomatsakis** [comment]
I took a stab at a draft of a charter, which you can find [in this HackMd document](https://hackmd.io/Bbf4ZcS6TLeCY7Wqd_mboA). Feedback welcome!

**Comment by gnunicorn** [comment]
@skade will put the current version to the vote and it might be published and this ticket closed, once that passed.
