### ISSUE TITLE
Tracker document to record status of repo audits, contact responses, and migrations so that move to rust-lang org can be completed

### ISSUE THREAD

**Issue by valgrimm** [rust-lang/wg-governance#30]
**META**
Originating issue: https://github.com/rust-lang/wg-governance/issues/4
Orginating meeting: https://hackmd.io/T-KVGkNfQpipFmTUiwS8tQ?both
HackMD: https://hackmd.io/wdJIYSUCTCWKoAfu3y8Q0w?both

**Comment by valgrimm** [comment]
Document complete and ready for use.

**Comment by XAMPPRocky** [comment]
Thank you, this is great! @nikomatsakis What do you think about, we send all those repos with one more ping, and after the next meeting (~2 weeks) we transfer whatever ones are remaining?

**Comment by valgrimm** [comment]
@XAMPPRocky @nikomatsakis Hi, do you need any help updating the document? If you need to you can forward a bunch of the email responses you receive my way and I can update the document accordingly.

**Comment by XAMPPRocky** [comment]
@valgrimm Hey, I haven't gotten around this yet. What I'll do is make time to create similar issue for working groups to the team tracking issue https://github.com/rust-lang/team/issues/146 and then ping the remaining teams and then use your document to track the responses. Since we could get responses from GitHub, email, discord, or some other service.

**Comment by valgrimm** [comment]
@XAMPPRocky Ah ok, good to know. I could help create issues and, if it would be ok, track the responses on Github. Would that be helpful? I'd have volunteered to do more earlier, but I was trying to identify a gap where I could contribute, as I know this is a situation where known people need to do the actual notifying.

**Comment by XAMPPRocky** [comment]
@valgrimm There's always more work, but you shouldn't feel any pressure to contribute more than you feel you're able to. You could go through the `rust-lang-nursery` and other organisations that we mentioned in the [minutes](https://github.com/rust-lang/wg-governance/blob/master/minutes/2019.12.03.md) and the [issue](https://github.com/rust-lang/wg-governance/issues/4#issuecomment-525473025). And make an issue for any that don't already have issues for them. All of the issues I created look like this with the same title so it should be easy to find an issue if it exists. https://github.com/rust-lang-nursery/rust-cookbook/issues/558

**Comment by valgrimm** [comment]
Thank you @XAMPPRocky, for all of the above (: And I'll get to some of that creating issues this evening after work (CET), if there are any left.

**Comment by XAMPPRocky** [comment]
Superceded by #50
