### ISSUE TITLE
Publish Survey results

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/wg-governance#8]
[Link to survey](https://docs.google.com/forms/d/1PL89rYOhscDHWnedx6QPXTH5eKjtVGHRbU5zjlwnAIU/edit#responses) (can't access? ping @jonathandturner  )

Read through and answer: _What are the three main take aways from the comments for you_?

Come up with a blog post(?) publishing some insights into the results and key take aways:
 1. show aggregated data
 2. if we publish quoted, we paraphrase to obfuscate the source
 3. what are key points we take out of this and what does that mean for this team and how it works?

**Comment by gnunicorn** [comment]
My take away are the known few:

 1. missing processes, in particular regarding the RFC as well as the inter-team-communications
 2. lack of time, commitment of people to work on things (processes and clearer expectations might encourage more responsible behavior here) 
 3. problems organizing meetings, staying up to date and keeping everyone in the loop

**Comment by nikomatsakis** [comment]
Talked to @jonathandturner -- survey data is available (though it requires granting access, due to privacy concerns) but a report needs to be written. He doesn't have time at the moment though so we should figure out who will do it. I recall going through the data at some point and taking notes, but I'd have to find those. =)

**Comment by BatmanAoD** [comment]
I have volunteered to draft a blog post from the survey data.

**Comment by XAMPPRocky** [comment]
This doesn't seem to making any progress, so I'm going to close it, if someone wants to take it back up we can re-open.
